### ISSUE TITLE
When creating new path, provide user with link/button to creating new chapters if they don't have any

### ISSUE THREAD

**Issue by oleeskild** [oleeskild/WebNovel#4]
When the user is creating a new path but doesn't have any drafts to put in the nodes, there should exist some explanation as to how the user can create these chapters.

**Comment by andrmos** [comment]
Får du det til?
Hvordan er varmen?
JAFU savner deg.
Klem.

**Comment by oleeskild** [comment]
Haha
Jepp
Meget deilig
Så koselig, jeg savner JAFU
Klem og koz
